from typing import List, Dict, Any, Optional
from uuid import UUID
from pydantic import BaseModel, Field
from enum import Enum

# --- Enums ---

class QueryComplexity(str, Enum):
    SIMPLE = "SIMPLE"
    MEDIUM = "MEDIUM"
    COMPLEX = "COMPLEX"

class ToolStatus(str, Enum):
    SUCCESS = "SUCCESS"
    FAILED = "FAILED"


# --- Schemas ---

class UserContext(BaseModel):
    user_id: str = Field(..., description="Unique identifier for the user.")
    role: str = Field(..., description="Role-based access control level.")
    authorized_groups: List[str] = Field(default_factory=list, description="Groups user is authorized to access.")


class UserRequest(BaseModel):
    query_id: UUID = Field(..., description="UUID identifying the query request.")
    session_id: UUID = Field(..., description="UUID tracking the user session.")
    raw_query: str = Field(..., description="Original raw query query string.")
    user_context: UserContext = Field(..., description="Security context metadata of the user.")


class CanonicalQuery(BaseModel):
    query_id: UUID = Field(..., description="UUID identifying the query request.")
    canonical_text: str = Field(..., description="Cleaned, standardized user query.")
    intent_class: str = Field(..., description="Classified intent class.")
    complexity: QueryComplexity = Field(..., description="Complexity mapping for routing query.")
    rewritten_queries: List[str] = Field(default_factory=list, description="Queries generated via expansion/rewriting.")
    pii_safe: bool = Field(..., description="True if no PII is detected in the query.")


class DocumentMetadata(BaseModel):
    url: Optional[str] = Field(None, description="Source URL reference.")
    page_number: Optional[int] = Field(None, description="Page number details.")
    last_modified: Optional[str] = Field(None, description="Last modification timestamp.")


class DocumentChunk(BaseModel):
    document_id: str = Field(..., description="Identifier for the source document.")
    chunk_id: str = Field(..., description="Identifier for this specific chunk.")
    text: str = Field(..., description="The textual content of the chunk.")
    similarity_score: float = Field(..., description="Vector similarity search score.")
    rerank_score: float = Field(..., description="Score generated by cross-encoder re-ranking.")
    source_metadata: DocumentMetadata = Field(default_factory=DocumentMetadata, description="Extracted metadata fields.")


class TaskStep(BaseModel):
    step_id: int = Field(..., description="Order index of this step in reasoning flow.")
    description: str = Field(..., description="Detailed step activity description.")
    tool_selected: str = Field(..., description="Name of the selected tool.")
    arguments: Dict[str, Any] = Field(default_factory=dict, description="Arguments passed to the tool.")
    status: ToolStatus = Field(..., description="Status execution flag.")
    observation: str = Field(..., description="Result of the tool execution.")


class AgentTrace(BaseModel):
    task_steps: List[TaskStep] = Field(default_factory=list, description="List of individual tasks executed.")
    aggregated_evidence: List[str] = Field(default_factory=list, description="Consolidated evidence gathered.")
    need_more_evidence: bool = Field(default=False, description="Flag indicating if reasoning loop needs more data.")


class ValidationResult(BaseModel):
    is_safe: bool = Field(..., description="True if output meets compliance guidelines.")
    pii_detected: bool = Field(..., description="True if PII leaks are detected in response.")
    toxicity_detected: bool = Field(..., description="True if toxic content is detected in output.")
    groundedness_score: float = Field(..., description="Groundedness verification score.")
    hallucination_detected: bool = Field(..., description="True if response content contains hallucinations.")
    confidence_score: float = Field(..., description="System score reflecting certainty of response correctness.")
    requires_human_review: bool = Field(..., description="True if score requires manual routing to review queue.")


# --- Ingestion & Retrieval API Schemas ---

class MetadataFilter(BaseModel):
    document_id: Optional[str] = Field(None, description="Filter by specific document ID.")
    metadata_equals: Dict[str, Any] = Field(default_factory=dict, description="Key-value pairs to match in source_metadata JSONB.")


class RetrievalQuery(BaseModel):
    query_text: str = Field(..., description="User search query string.")
    top_k: int = Field(5, ge=1, le=100, description="Maximum number of chunks to retrieve.")
    score_threshold: float = Field(0.0, ge=0.0, le=1.0, description="Minimum similarity threshold (0.0 to 1.0).")
    filter: Optional[MetadataFilter] = Field(None, description="Optional metadata filter rules.")


class RetrievalResultItem(BaseModel):
    chunk_id: str = Field(..., description="Child chunk identifier.")
    parent_id: str = Field(..., description="Parent chunk identifier.")
    document_id: str = Field(..., description="Document identifier.")
    chunk_text: str = Field(..., description="Text of matching child chunk.")
    parent_text: str = Field(..., description="Full text of parent chunk context.")
    similarity_score: float = Field(..., description="Cosine similarity score (0.0 to 1.0).")
    source_metadata: Dict[str, Any] = Field(default_factory=dict, description="Metadata dictionary.")


class RetrievalResult(BaseModel):
    query_text: str = Field(..., description="The queried text.")
    total_retrieved: int = Field(..., description="Number of items returned.")
    items: List[RetrievalResultItem] = Field(default_factory=list, description="Top matching chunk results.")


class IngestionResponse(BaseModel):
    document_id: str = Field(..., description="Unique document ID created or passed.")
    filename: str = Field(..., description="Original filename.")
    storage_path: str = Field(..., description="Path in object storage.")
    parent_chunks_count: int = Field(..., description="Number of parent chunks generated.")
    child_chunks_count: int = Field(..., description="Number of child chunks generated and embedded.")

