from typing import List, Dict, Any, Optional
from uuid import UUID
from pydantic import BaseModel, Field
from enum import Enum

# --- Enums ---

class QueryComplexity(str, Enum):
    SIMPLE = "SIMPLE"
    MEDIUM = "MEDIUM"
    COMPLEX = "COMPLEX"

class ToolStatus(str, Enum):
    SUCCESS = "SUCCESS"
    FAILED = "FAILED"


# --- Schemas ---

class UserContext(BaseModel):
    user_id: str = Field(..., description="Unique identifier for the user.")
    role: str = Field(..., description="Role-based access control level.")
    authorized_groups: List[str] = Field(default_factory=list, description="Groups user is authorized to access.")


class UserRequest(BaseModel):
    query_id: UUID = Field(..., description="UUID identifying the query request.")
    session_id: UUID = Field(..., description="UUID tracking the user session.")
    raw_query: str = Field(..., description="Original raw query query string.")
    user_context: UserContext = Field(..., description="Security context metadata of the user.")


class CanonicalQuery(BaseModel):
    query_id: UUID = Field(..., description="UUID identifying the query request.")
    canonical_text: str = Field(..., description="Cleaned, standardized user query.")
    intent_class: str = Field(..., description="Classified intent class.")
    complexity: QueryComplexity = Field(..., description="Complexity mapping for routing query.")
    rewritten_queries: List[str] = Field(default_factory=list, description="Queries generated via expansion/rewriting.")
    pii_safe: bool = Field(..., description="True if no PII is detected in the query.")


class DocumentMetadata(BaseModel):
    url: Optional[str] = Field(None, description="Source URL reference.")
    page_number: Optional[int] = Field(None, description="Page number details.")
    last_modified: Optional[str] = Field(None, description="Last modification timestamp.")
    has_code_blocks: Optional[bool] = Field(False, description="True if chunk contains code blocks.")
    has_tables: Optional[bool] = Field(False, description="True if chunk contains tables.")
    image_refs: List[str] = Field(default_factory=list, description="Paths/URLs to embedded diagrams or images.")
    layout_type: Optional[str] = Field(None, description="Layout element type (code, table, heading, paragraph, diagram).")



class DocumentChunk(BaseModel):
    document_id: str = Field(..., description="Identifier for the source document.")
    chunk_id: str = Field(..., description="Identifier for this specific chunk.")
    text: str = Field(..., description="The textual content of the chunk.")
    similarity_score: float = Field(..., description="Vector similarity search score.")
    rerank_score: float = Field(..., description="Score generated by cross-encoder re-ranking.")
    source_metadata: DocumentMetadata = Field(default_factory=DocumentMetadata, description="Extracted metadata fields.")


class TaskStep(BaseModel):
    step_id: int = Field(..., description="Order index of this step in reasoning flow.")
    description: str = Field(..., description="Detailed step activity description.")
    tool_selected: str = Field(..., description="Name of the selected tool.")
    arguments: Dict[str, Any] = Field(default_factory=dict, description="Arguments passed to the tool.")
    status: ToolStatus = Field(..., description="Status execution flag.")
    observation: str = Field(..., description="Result of the tool execution.")


class AgentTrace(BaseModel):
    task_steps: List[TaskStep] = Field(default_factory=list, description="List of individual tasks executed.")
    aggregated_evidence: List[str] = Field(default_factory=list, description="Consolidated evidence gathered.")
    need_more_evidence: bool = Field(default=False, description="Flag indicating if reasoning loop needs more data.")


class ValidationResult(BaseModel):
    is_safe: bool = Field(..., description="True if output meets compliance guidelines.")
    pii_detected: bool = Field(..., description="True if PII leaks are detected in response.")
    toxicity_detected: bool = Field(..., description="True if toxic content is detected in output.")
    groundedness_score: float = Field(..., description="Groundedness verification score.")
    hallucination_detected: bool = Field(..., description="True if response content contains hallucinations.")
    confidence_score: float = Field(..., description="System score reflecting certainty of response correctness.")
    requires_human_review: bool = Field(..., description="True if score requires manual routing to review queue.")


# --- Ingestion & Retrieval API Schemas ---

class MetadataFilter(BaseModel):
    document_id: Optional[str] = Field(None, description="Filter by specific document ID.")
    metadata_equals: Dict[str, Any] = Field(default_factory=dict, description="Key-value pairs to match in source_metadata JSONB.")


class RetrievalQuery(BaseModel):
    query_text: str = Field(..., description="User search query string.")
    top_k: int = Field(5, ge=1, le=100, description="Maximum number of chunks to retrieve.")
    score_threshold: float = Field(0.0, ge=0.0, le=1.0, description="Minimum similarity threshold (0.0 to 1.0).")
    filter: Optional[MetadataFilter] = Field(None, description="Optional metadata filter rules.")
    mode: str = Field("hybrid", description="Retrieval mode: 'dense', 'sparse', or 'hybrid'.")
    rerank: bool = Field(True, description="True to enable cross-encoder reranking.")


class RetrievalResultItem(BaseModel):
    chunk_id: str = Field(..., description="Child chunk identifier.")
    parent_id: str = Field(..., description="Parent chunk identifier.")
    document_id: str = Field(..., description="Document identifier.")
    chunk_text: str = Field(..., description="Text of matching child chunk.")
    parent_text: str = Field(..., description="Full text of parent chunk context.")
    similarity_score: float = Field(..., description="Cosine similarity score (0.0 to 1.0).")
    rerank_score: float = Field(0.0, description="Cross-Encoder rerank score (0.0 to 1.0).")
    source_metadata: Dict[str, Any] = Field(default_factory=dict, description="Metadata dictionary.")


class RetrievalResult(BaseModel):
    query_text: str = Field(..., description="The queried text.")
    total_retrieved: int = Field(..., description="Number of items returned.")
    items: List[RetrievalResultItem] = Field(default_factory=list, description="Top matching chunk results.")


class IngestionResponse(BaseModel):
    document_id: str = Field(..., description="Unique document ID created or passed.")
    filename: str = Field(..., description="Original filename.")
    storage_path: str = Field(..., description="Path in object storage.")
    parent_chunks_count: int = Field(..., description="Number of parent chunks generated.")
    child_chunks_count: int = Field(..., description="Number of child chunks generated and embedded.")


class BatchIngestionResponse(BaseModel):
    total_files: int = Field(..., description="Total number of files submitted.")
    successful: int = Field(..., description="Number of files successfully ingested.")
    failed: int = Field(..., description="Number of files that failed ingestion.")
    results: List[IngestionResponse] = Field(default_factory=list, description="Ingestion responses for succeeded files.")
    errors: List[Dict[str, str]] = Field(default_factory=list, description="Error details for failed files.")



# --- Context Engineering & Generation Schemas (Stage 4 & 5) ---

class SourceLocation(BaseModel):
    start_char: Optional[int] = Field(None, description="Start character offset in cleaned source document.")
    end_char: Optional[int] = Field(None, description="End character offset in cleaned source document.")
    raw_start_char: Optional[int] = Field(None, description="Start character offset in raw source document file.")
    raw_end_char: Optional[int] = Field(None, description="End character offset in raw source document file.")
    start_line: Optional[int] = Field(None, description="Start line number (1-indexed).")
    end_line: Optional[int] = Field(None, description="End line number (1-indexed).")
    bbox: Optional[List[float]] = Field(None, description="Bounding box [x0, y0, x1, y1] for PDFs if available.")
    dom_selector: Optional[str] = Field(None, description="CSS/DOM selector for HTML elements.")


class CitationSource(BaseModel):
    index: int = Field(..., description="Citation index number for [Source N] notation.")
    document_id: str = Field(..., description="Source document identifier.")
    chunk_id: str = Field(..., description="Child chunk identifier used.")
    page_number: Optional[int] = Field(None, description="Page number in source document, if available.")
    file_type: str = Field("txt", description="File extension of source document (.pdf, .html, .txt, etc.).")
    similarity_score: float = Field(..., description="Cosine similarity score of this source.")
    text_snippet: str = Field("", description="Short snippet of the source text for UI highlighting.")
    parent_text: str = Field("", description="The full parent chunk context text.")
    location: Optional[SourceLocation] = Field(None, description="Detailed location offsets and line numbers for dynamic highlighting.")
    image_refs: List[str] = Field(default_factory=list, description="Paths/URLs to embedded diagrams or images associated with this source.")
    has_code_blocks: bool = Field(False, description="True if source chunk contains code blocks.")
    has_tables: bool = Field(False, description="True if source chunk contains tables.")




class FormattedContext(BaseModel):
    evidence_blocks: List[str] = Field(default_factory=list, description="Numbered evidence text blocks: '[Source 1]: ...'")
    citations: List[CitationSource] = Field(default_factory=list, description="Citation provenance map.")
    total_tokens: int = Field(0, description="Token count of combined context.")
    truncated: bool = Field(False, description="Whether context was truncated to fit token budget.")


class PromptPayload(BaseModel):
    system_message: str = Field(..., description="System prompt with role and rules.")
    user_message: str = Field(..., description="User query with formatted context.")
    context_tokens: int = Field(0, description="Token count of the context portion.")


class TokenUsage(BaseModel):
    prompt_tokens: int = Field(0, description="Tokens consumed by the prompt.")
    completion_tokens: int = Field(0, description="Tokens generated in the response.")
    total_tokens: int = Field(0, description="Total tokens consumed.")


class QueryTrace(BaseModel):
    intent_class: str = Field("FACTUAL", description="Classified intent class (FACTUAL, STATISTICAL, COMPARATIVE, CONCEPTUAL, etc.).")
    complexity: QueryComplexity = Field(QueryComplexity.SIMPLE, description="Query complexity routing level (SIMPLE, MEDIUM, COMPLEX).")
    pii_safe: bool = Field(True, description="True if no PII detected in user query.")
    sanitized_query: str = Field("", description="Cleaned, PII-redacted query string.")
    rewritten_queries: List[str] = Field(default_factory=list, description="Query variations generated for search.")
    hyde_passage: Optional[str] = Field(None, description="Hypothetical document passage generated for HyDE retrieval.")


class GenerationResult(BaseModel):
    answer: str = Field(..., description="The generated LLM answer with inline [Source N] citations.")
    citations: List[CitationSource] = Field(default_factory=list, description="Citation provenance map.")
    token_usage: TokenUsage = Field(default_factory=TokenUsage, description="Token consumption metrics.")
    retrieval_count: int = Field(0, description="Number of chunks retrieved from vector store.")
    latency_ms: float = Field(0.0, description="End-to-end pipeline latency in milliseconds.")
    model_used: str = Field("", description="LLM model identifier used for generation.")
    query_trace: Optional[QueryTrace] = Field(None, description="Query understanding trace (intent, complexity, expansion, HyDE).")


class QueryRequest(BaseModel):
    query_text: str = Field(..., description="Natural language user question.")
    top_k: int = Field(5, ge=1, le=50, description="Maximum number of chunks to retrieve.")
    score_threshold: float = Field(0.0, ge=0.0, le=1.0, description="Minimum similarity score threshold.")
    stream: bool = Field(False, description="If true, response is streamed via SSE.")
    provider: str = Field("deepseek", description="LLM provider: 'deepseek' or 'openai'.")


class DocumentItem(BaseModel):
    document_id: str = Field(..., description="The unique document identifier.")
    filename: str = Field(..., description="The original filename of the document.")
    created_at: str = Field(..., description="ISO formatted creation timestamp.")
    storage_path: Optional[str] = Field(None, description="Path where the original document is stored.")
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Metadata key-values associated with the document.")

